name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Set up PostgreSQL service for tests
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: claims_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run type check
      run: npm run type-check

    - name: Set up test database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d claims_test -f supabase/migrations/00000000000000_initial_schema.sql
        PGPASSWORD=postgres psql -h localhost -U postgres -d claims_test -f supabase/migrations/*_update_claims_schema.sql

    - name: Run tests
      env:
        SUPABASE_URL: http://localhost:54321
        SUPABASE_SERVICE_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzE5NzQxNCwiZXhwIjoyNTQ3ODQyMjk0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.39z3-t3hHHH3Rw3qhH4jN4G1QvxHrMzKR3_8DYbhzjw
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: claims_test
      run: npm test

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/